def isnum(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
li = ["10","23","34","a"]
a = map(isnum,li)
list(a)


In [7]:
a= filter(isnum,li)
list(a)

['10', '23', '34']

### ***Lambda***:

In [9]:
def sum1(a,b):
    c=a+b
    return c
sum1(1,9)



10

In [10]:
a= lambda x,y :x+y
a(4,5)

9

In [11]:
def squareof(a):
    b=a*a
    return b
squareof(19)


361

In [12]:
a=lambda x:x*x
a(5)

25

### List Comperhension

In [2]:
a= int(input("enter num"))
for i in range (0,a+1):
    print(i**2)

enter num8
0
1
4
9
16
25
36
49
64


In [4]:
a=[i**2 for i in range (1,9)]
a

[1, 4, 9, 16, 25, 36, 49, 64]

In [4]:
def factorial(n):
    fact=1
    for i in range(1,n+1):
        fact=fact*i
    print("the factorial of",n,"is",fact)

In [5]:
factorial(19)


the factorial of 19 is 121645100408832000


In [2]:
a= int(input())
b=1
for i in range (1,a+1):
    b*=i
print(b)    


5
120


In [2]:
import math 
s=[math.factorial(i) for i in range (1,19)]
s

[1,
 2,
 6,
 24,
 120,
 720,
 5040,
 40320,
 362880,
 3628800,
 39916800,
 479001600,
 6227020800,
 87178291200,
 1307674368000,
 20922789888000,
 355687428096000,
 6402373705728000]

In [6]:
n= int (input())
m=10
l=[n*i for i in range (1,m+1)]
l


19


[19, 38, 57, 76, 95, 114, 133, 152, 171, 190]

### Flie Handling


* Performing operations on a file is called File Handling.
* Entering some data to a file is called as write to a file. 
* Retrieving data from a file is called as reading from a file.
* We can perform append,delete operations on file.

In [4]:
def writetoafile(filename,data):
    with open(filename,"w") as m:
        m.write(data)
    return
filename="data.txt"
writetoafile(filename,"mona\nanupottipeddaadava\nteju\n")
        

In [5]:
def readtoafile(filename,data):
    with open(filename,"w") as m:
        am=m.read()
        m.close()
    return am  
readfromafile("data.txt")

'mona\nanupottipeddaadava\nteju\n'

In [10]:
def readfromafile(filename):
    with open(filename,"r") as m:
        am=m.read()
        m.close()
    return am
filename="data.txt"
readfromafile("data.txt")
def printlines(filename):
    with open(filename,"r") as m:
        for line in m:
            print(line,end="")
    return
printlines(filename)
print(readfromafile(filename))

mona
anupottipeddaadava
teju
mona
anupottipeddaadava
teju



In [11]:
def readfromafile(filename):
    with open(filename,"r") as m:
        am=m.read()
        m.close()
    return am
filename="mona.txt"
readfromafile("mona.txt")
def printlines(filename):
    with open(filename,"r") as m:
        for line in m:
            print(line,end="")
    return
#printlines(filename)
print(readfromafile(filename))

def multipletwonums(a,b):
    a=int(input())
    b=int(input())
    c=a*b
    return
multipletwonums(4,5)    
    



In [55]:
def appendtofile(filename,data):
    with open(filename,"a") as m:
        for line in data:
            m.write("\n"+line)
        return
data=["teju4gputta","anupenta","teju3gcheta"]
filename="data.txt"
appendtofile(filename,data)

### ***Numpy***

* ***Numpy is an advance libraray.***
* ***Numpy---Numerical python.***
* ***Numpy is to perform mathematical and stastical operations.***
* ***The value are represented in the form of rows and columns.***
* ***Advantages of Numpy when compared to lists:


* ***Advantages of Numpy when compared to lists:***
    * ***It takes less time***
    * ***Perforame will be high***
    * ***Occupies less memory***

In [1]:
import numpy as mp

In [3]:
a = mp.array([1,2,3,4])
a.size

4

In [9]:
### creating an array in partical range 
a=mp.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
a=mp.arange(1,20)
type(a)

numpy.ndarray

In [10]:
### check the number of elements
a.size

19

In [12]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [14]:
a-1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [15]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [17]:
a2=mp.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
a2.size

8

In [22]:
mp.arange(6,9)


array([6, 7, 8])

In [23]:
a2=mp.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [24]:
a2.dtype

dtype('complex128')

In [25]:
a.dtype

dtype('int32')

In [30]:
a1=mp.arange(3,4)+mp.arange(4,9)
a1

array([ 7,  8,  9, 10, 11])

In [39]:
### comparision of two arraysa 
a= mp.array([[1,2,3,4],[5,6,7,8]])
b= mp.array([[4,5,6,7],[3,8,7,6]])            

In [40]:
a>b

array([[False, False, False, False],
       [ True, False, False,  True]])

In [41]:
a==b

array([[False, False, False, False],
       [False, False,  True, False]])

In [42]:
a+b

array([[ 5,  7,  9, 11],
       [ 8, 14, 14, 14]])

In [43]:
a-b

array([[-3, -3, -3, -3],
       [ 2, -2,  0,  2]])

In [45]:
a**b

array([[      1,      32,     729,   16384],
       [    125, 1679616,  823543,  262144]], dtype=int32)

In [46]:
a*b

array([[ 4, 10, 18, 28],
       [15, 48, 49, 48]])

In [57]:
a<b


array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [47]:
a/ab

array([[0.25      , 0.4       , 0.5       , 0.57142857],
       [1.66666667, 0.75      , 1.        , 1.33333333]])

In [48]:
a//b

array([[0, 0, 0, 0],
       [1, 0, 1, 1]], dtype=int32)

In [51]:
mp.ones([(6,6)]dtype=int)

SyntaxError: invalid syntax (<ipython-input-51-90c4fee8fcd7>, line 1)

In [54]:
mp.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
a[0]

array([1, 2, 3, 4])

In [60]:
a[0:1,1:2] ### a[startingrow:endingrow,staringcolumn:endingcolumn]

array([[2]])

In [62]:
a[1:2,2:3]

array([[7]])

In [65]:
a[:,1:3]

array([[2, 3],
       [6, 7]])

In [66]:
a[:,2:3]

array([[3],
       [7]])

In [68]:
a[1:,1:]

array([[6, 7, 8]])

In [69]:
a[:1,1:]

array([[2, 3, 4]])

In [70]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
a.shape

(2, 4)

In [72]:
a.ndim

2

In [73]:
a.nbytes

32

In [74]:
a.itemsize

4

In [85]:
b=mp.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [86]:
b.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [87]:
max(b)

8

In [88]:
mp.std(b)

1.707825127659933

In [89]:
mp.mean(b)

5.5

In [90]:
mp.sum(b)

33

In [91]:
mp.var(b)

2.9166666666666665

In [92]:
mp.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [93]:
b

array([3, 4, 5, 6, 7, 8])

In [94]:
mp.argmin(b)

0

In [95]:
mp.argmax(b)

5

In [98]:
a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [99]:
b.transpose()

array([3, 4, 5, 6, 7, 8])

In [103]:
### decimal to binary 
def decimaltobinary(n):
    if n>1:
        decimaltobinary(n//2)
    print(n%2,end=" ")
n=int(input("enter any decimal number:"))
decimaltobinary(n)

enter any decimal number:20
1 0 1 0 0 